plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.147'
}

group = 'dev.zeli.mallardguard'
version = mod_version
base { archivesName = 'mallardguard' }
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = neo_version
    runs {
        client { client() }
        server { server(); programArgument '--nogui' }
    }
    mods {
        mallardguard { sourceSet(sourceSets.main) }
    }
}

tasks.named('processResources', ProcessResources) {
    def values = [version: project.version.toString()]
    inputs.properties values
    filesMatching('META-INF/neoforge.mods.toml') { expand values }
}
