modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="mallardguard"
version="${version}"
displayName="Mallard Guard - Immersive Parrying"
authors="z.eli_"
description="A configurable parry and guard system."
logoFile="mallardguard.png"

[[dependencies.mallardguard]]
modId="neoforge"
type="required"
versionRange="[21.1.248,)"
ordering="NONE"
side="BOTH"

[[dependencies.mallardguard]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
